### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Cooctus**
You misspelled something

### CODE REVIEW

**Comment by Cooctus** [comment]
Made it easier for users to understand

**Comment by Cooctus** [comment]
You know you should be kinder to your contributors

**Comment by poespas** [comment]
I had trouble with reading the description of the repo, but after this change, everything is different, thanks for the clarification!

**Comment by Cooctus** [comment]
That's great glad I could help!

**Comment by poespas** [comment]
Actually, i had another question, why dont you use php?

**Comment by Cooctus** [comment]
Because PHP is for insane masochists.

**Comment by poespas** [comment]
# Ok 
**thanks** 
[for](urmomxd) 
`your` 

1. 

info

**Comment by Cooctus** [comment]
No problem my dude anytime :D

**Pull request merged**
